language: php

php:
  - 7.2

matrix:
  fast_finish: true

  allow_failures: []

  include:

    - php: "7.2"
      dist: trusty
      
    - php: "7.2"
      dist: bionic

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  global:
    - APPLICATION_ENV=development
    - APPLICATION_STORE=DE

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction --prefer-dist

script:
  - php -r "var_dump(glob(__DIR__ . '/tests/SprykerTest/Shared/Twig/Fixtures/vendor/*/*/src/CoreNamespace/Yves/Bundle/Theme/default', GLOB_ONLYDIR | GLOB_NOSORT));"

notifications:
  email: false
